Add in some tips and workarounds for problems (S1X)
XLabsProject/XLabsProject.github.io pull request #78
Opened 2021-12-24 21:17 UTC by Pawlicker

I've added in some tips and workarounds from problems I've run into from hosting an S1X server myself, along with system requirements I've seen in the real world. I've also added in a link to the S1X logger script as this is needed for admin tools to work.

## Pull request type

 

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Other information

2021-12-24 23:11 UTC, diamante0018 requested changes

2021-12-24 23:11 UTC, diamante0018 commented on support_s1x_server.html
> +										<a
What is wrong with how formatting was before?

2021-12-24 23:11 UTC, diamante0018 commented on support_s1x_server.html
> +										in the map rotation, etc.</li>
You could explain better what it means 'on the rotate' or' in the map rotation' to a user reading the guide. It doesn't feel like this bit is an improvement, unless your goal was to change the meaning of the sentence.

2021-12-24 23:11 UTC, diamante0018 commented on support_s1x_server.html
> +										entering the console, and typing in
Elaborate `entering the console` It doesn't make sense to me. 
You could mention how to open the console, what to do if the tilde key is not present on your keyboard, etc...

2021-12-24 23:11 UTC, diamante0018 commented on support_s1x_server.html
> +										logging simply will not work.</li>
I feel like the word 'simply' doesn't fit well in this sentence.

2021-12-24 23:11 UTC, diamante0018 commented on support_s1x_server.html
> +										function. For downloads and more information, please visit <a
Random formatting change I guess?

2021-12-25 17:02 UTC, Pawlicker commented on support_s1x_server.html
> +										function. For downloads and more information, please visit <a
Sorry about that, I edited it in Expression Web and it changed the formatting for some reason.

2021-12-25 22:26 UTC, ChxseH commented on support_s1x_server.html
> +										in the map rotation, etc.</li>
"in the rotation" makes more sense in this instance

2021-12-25 22:42 UTC, merged