Update map porting to the newer tools
XLabsProject/XLabsProject.github.io pull request #87
Opened 2022-12-16 15:09 UTC by Rackover

## Pull request type

 

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Other (please describe): 

![image](https://user-images.githubusercontent.com/33836535/208127838-bcaaf84d-222f-4688-93d0-99836219b42d.png)

![image](https://user-images.githubusercontent.com/33836535/208127891-cee1d989-1391-40f1-8dd9-1406c9398fb8.png)

![image](https://user-images.githubusercontent.com/33836535/208127920-0df06bb3-cc39-44f7-906b-b036b1c1369b.png)

![image](https://user-images.githubusercontent.com/33836535/208127953-26f8f133-09d2-44b6-8245-88e254db22df.png)

2022-12-27 22:02 UTC, Dss0 approved these changes

2022-12-28 10:56 UTC, diamante0018 requested changes
`check out mixed line endings and spaces vs tabs`
`there is probably a mix of two in the document`

2022-12-30 20:28 UTC, diamante0018 approved these changes
I a:b::b:rove

2022-12-31 13:49 UTC, momo5502 commented
Still wish more effort was put into making a good looking UI, but who am I to judge.

2022-12-31 13:49 UTC, merged